[package]
org = "ballerinax"
name = "ibm.ibmmq"
version = "1.4.2"
authors = ["Ballerina"]
keywords = ["ibm.ibmmq", "client", "messaging", "network", "pubsub", "Vendor/IBM", "Area/Communication", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ibm.ibmmq"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ibm.ibmmq-native"
version = "1.4.2"
path = "../native/build/libs/ibm.ibmmq-native-1.4.2-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.json"
artifactId = "json"
version = "20231013"
path = "./lib/json-20231013.jar"

[[platform.java21.dependency]]
groupId = "com.ibm.mq"
artifactId = "com.ibm.mq.allclient"
version = "9.4.1.0"
path = "./lib/com.ibm.mq.allclient-9.4.1.0.jar"
scope = "provided"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.15.3"
path = "./lib/jackson-annotations-2.15.3.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.15.3"
path = "./lib/jackson-core-2.15.3.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.15.3"
path = "./lib/jackson-databind-2.15.3.jar"

[[platform.java21.dependency]]
groupId = "javax.jms"
artifactId = "javax.jms-api"
version = "2.0.1"
path = "./lib/javax.jms-api-2.0.1.jar"
